import random
import time



front_words = ['Neo-','Anti-', 'Retro-','Cyber-','Pan-', 'Techno-','Bio-', 'Ultra-', 'Pseudo-','Capital-','Future-','De-','Post-','Pre-','Semi-','Synthetic-','Nano-','Hyper-','Psycho-','Sacred ','Temporal-','Theo-','Macro-','Micro-','Politico-','Quasi-', 'Meta-', 'Cultural ', 'Eco-', 'Social ', 'Electro-', 'Xeno-']
mid_words = ['linear',
'left',
'right',
'central',
'accelerationist',
'territorial',
'new',
'terminal',
'paranoid',
'fictional',
'functional',
'electronic',
'fortified',
'digital',
'divine',
'cyber',
'embedded',
'positive',
'negative',
'integrated',
'form',
'dialectical',
'dynamic',
'grid',
'historical',
'human',
'political',
'virtual',
'unconscious',
'dimensional',
'reprogrammed',
'programmed',
'functional',
'navigational',
'sophisticated',
'industrial',
'economic',
'soft',
'bacterial',
'accumulative',
'biblical',
'extreme',
'conspiratorial',
'global',
'eternal',
'absurdist',
'anonymous',
'behavioural',
'existential',
'material',
'communal',
'automatic',
'populist',
'parallel',
'modern',
'operational',
'intangible',
'suburban',
'radical',
'state',
'planetary',
'abstract',
'surrealist',
'raw',
'celestial',
'gender',
'national',
'modular',
'reverse',
'remote',
'order',
'galactic',
'ecology',
'Rational',
'interactive',
'emergent',
'disorder',
'compressed',
'cloned',
'lateral'
]

end_wordsI = [
'Futurist',
'Cybernetic',
'Logic',
'Paradox',
'Culture',
'Capital',
'Imperialism',
'Civilisation',
'Capitalism',
'Time',
'Decolonisation',
'Initiative',
'Chaos',
'Invasion',
'Disease',
'Life-cycle',
'Monarchism',
'Democracy',
'Resistance',
'Map',
'Megacity',
'Metropolis',
'Control',
'Security',
'Drugs',
'Space',
'Structure',
'Sprawl',
'Military',
'Cyberspace',
'God',
'Settlement',
'Site',
'Citizenship',
'Market',
'Oppression',
'Conspiracy',
'Paranoia',
'Politics',
'Ritual',
'Consumerism',
'Theory',
'Matrix',
'Expansion',
'Waste',
'Distraction',
'Residue',
'Preservation',
'Collapse',
'Filter',
'Software',
'Process',
'Fragment',
'Topology',
'Module',
'Mainframe',
'Memory',
'Media',
'Recursion',
'Strategy',
'Communication',
'Interface',
'Reality',
'Sphere',
'Cartography',
'Colony',
'Influence',
'Continuity',
'Depression',
'Enclave',
'Zone',
'Divide',
'Virus',
'Enigma',
'Language',
'Abduction',
'Fiction',
'Repetition',
'Object',
'Authority',
'Symptom',
'Feedback',
'Tradition',
'Domination',
'Condition',
'System',
'Doctrine',
'Archetype',
'Singularity',
'Geography',
'Circuit',
'Intelligence',
'Pollution',
'Data',
'Transfer',
'Spaceship',
'Globalisation',
'Institution',
'War',
'Weapon',
'Agent',
'Alienation',
'Analysis',
'Amnesia',
'Conflict',
'Anomaly',
'Aesthetic',
'Anarchism',
'Primitivism',
'Realism',
'Automatism',
'Cognitivism',
'Collectivism',
'Dogma',
'Humanism',
'Mechanism',
'Mysticism',
'Utopia',
'Dystopia',
'Demagogue',
'Irony',
'Insurrection',
'Cyborg',
'Construct',
'Design',
'Regulation',
'Domestication',
'Cult',
'Deterrent',
'Web',
'Efficiency',
'Alliance',
'Theft',
'Species',
'Body',
'Empire',
'Deregulation',
'Arms-race',
'Engineering',
'Replication',
'Flood',
'Spasm',
'Screen'
]

misc_words = ['communist ',
'fascist ',
'liberal ',
'sexual ',
'alternative ',
'ancient ',
'fictional ',
'real ',
'disrupted ',
'western ',
'eastern ',
'systemic ',
'rebel ',
'revolutionary ',
'local ',
'universal ',
'unified ',
'cryptic ',
'corrupt ',
'drone ',
'nebulous ',
'underground ',
'covert ',
'government ',
'infinity ',
'dark ',
'russian ',
'chinese ',
'american ',
'european ',
'japanese ',
'asian ',
'african ',
'plasma ',
'organic ',
'rift ',
'renaissance ',
'continental ',
'international ',
'phase ',
'relapse ',
'voodoo ',
'flatline ',
'demon '
]

try:

    for x in range(0, 10000):

        new_word1 = random.choice(front_words) + random.choice(mid_words) + ' ' + random.choice(end_wordsI)
        new_word2 = random.choice(misc_words) + random.choice(mid_words) + ' ' + random.choice(end_wordsI)
        new_word3 = random.choice(misc_words) + random.choice(end_wordsI)
        new_word4 = random.choice(mid_words) + ' ' + random.choice(end_wordsI)
        new_word5 = random.choice(front_words) + random.choice(end_wordsI)
        new_word6 = random.choice(front_words) + random.choice(misc_words) + random.choice(end_wordsI)
        new_word7 = random.choice(mid_words) + ' ' + random.choice(end_wordsI)


        #time.sleep(2)

        print new_word1.title()
        print new_word2.title()
        print new_word3.title()
        print new_word4.title()
        print new_word5.title()
        print new_word6.title()
        print new_word7.title()




except KeyboardInterrupt:
    pass
